// Auto-generated by tools/prepare_assets.py from experiment/ten.json — do not edit.
window.SEGMENTS = [
 {
  "id": 1,
  "part": "国风-周南-关雎",
  "title_en": "Zhou Nan · Guan Ju",
  "title_zh": "周南·关雎",
  "title_short": "The Ospreys",
  "ancient": "关关雎鸠、在河之洲。\n窈窕淑女、君子好逑。",
  "translation": "Guan-guan go the ospreys,\nOn the islet in the river. \nThe modest, retiring, virtuous, young lady: \nFor our prince a good mate she."
 },
 {
  "id": 2,
  "part": "国风-周南-关雎",
  "title_en": "Zhou Nan · Guan Ju",
  "title_zh": "周南·关雎",
  "title_short": "The Ospreys",
  "ancient": "参差荇菜、左右流之。\n窈窕淑女、寤寐求之。\n求之不得、寤寐思服。\n悠哉悠哉、辗转反侧。",
  "translation": "Here long, there short, is the duckweed, \nTo the left, to the right, borne about by the current. \nThe modest, retiring, virtuous, young lady: \nWaking and sleeping, he sought her. \nHe sought her and found her not, \nAnd waking and sleeping he thought about her. \nLong he thought; oh! long and anxiously; \nOn his side, on his back, he turned, and back again."
 },
 {
  "id": 3,
  "part": "国风-周南-关雎",
  "title_en": "Zhou Nan · Guan Ju",
  "title_zh": "周南·关雎",
  "title_short": "The Ospreys",
  "ancient": "参差荇菜、左右采之。\n窈窕淑女、琴瑟友之。\n参差荇菜、左右芼之。\n窈窕淑女、锺鼓乐之。",
  "translation": "Here long, there short, is the duckweed; \nOn the left, on the right, we gather it. \nThe modest, retiring, virtuous, young lady: \nWith lutes, small and large, let us give her friendly welcome. \nHere long, there short, is the duckweed; \nOn the left, on the right, we cook and present it. \nThe modest, retiring, virtuous, young lady: \nWith bells and drums let us show our delight in her."
 },
 {
  "id": 4,
  "part": "国风-秦风-蒹葭",
  "title_en": "Qin Feng · Jian Jia",
  "title_zh": "秦风·蒹葭",
  "title_short": "Reeds and Rushes",
  "ancient": "蒹葭苍苍、白露为霜。\n所谓伊人、在水一方。\n遡洄从之、道阻且长。\n遡游从之、宛在水中央。",
  "translation": "The reeds and rushes are deeply green,\nAnd the white dew is turned into hoarfrost.\nThe man of whom I think,\nIs somewhere about the water.\nI go up the stream in quest of him,\nBut the way is difficult and long.\nI go down the stream in quest of him,\nAnd lo! he is right in the midst of the water."
 },
 {
  "id": 5,
  "part": "国风-秦风-蒹葭",
  "title_en": "Qin Feng · Jian Jia",
  "title_zh": "秦风·蒹葭",
  "title_short": "Reeds and Rushes",
  "ancient": "蒹葭凄凄、白露未晞。\n所谓伊人、在水之湄。\n遡洄从之、道阻且跻。\n遡游从之、宛在水中坻。",
  "translation": "The reeds and rushes are luxuriant,\nAnd the white dew is not yet dry.\nThe man of whom I think,\nIs on the margin of the water.\nI go up the stream in quest of him,\nBut the way is difficult and steep.\nI go down the stream in quest of him,\nAnd lo! he is on the islet in the midst of the water."
 },
 {
  "id": 6,
  "part": "国风-秦风-蒹葭",
  "title_en": "Qin Feng · Jian Jia",
  "title_zh": "秦风·蒹葭",
  "title_short": "Reeds and Rushes",
  "ancient": "蒹葭采采、白露未已。\n所谓伊人、在水之涘。\n遡洄从之、道阻且右。\n遡游从之、宛在水中沚。",
  "translation": "The reeds and rushes are abundant,\nAnd the white dew is not yet ceased.\nThe man of whom I think,\nIs on the bank of the river.\nI go up the stream in quest of him,\nBut the way is difficult and turns to the right.\nI go down the stream in quest of him,\nAnd lo! he is on the island in the midst of the water."
 },
 {
  "id": 7,
  "part": "小雅-鹿鸣之什-采薇",
  "title_en": "Xiao Ya · Cai Wei",
  "title_zh": "小雅·采薇",
  "title_short": "Gathering Vetch",
  "ancient": "采薇采薇、薇亦作止。\n曰归曰归、岁亦莫止。\n靡室靡家、猃狁之故。\n不遑启居、猃狁之故。",
  "translation": "Let us gather the thorn-ferns, let us gather the thorn-ferns;\nThe thorn-ferns are now springing up.\nWhen shall we return? When shall we return?\nIt will be late in the [next] year.\nWife and husband will be separated,\nBecause of the Xian-yun.\nWe shall have no leisure to rest,\nBecause of the Xian-yun."
 },
 {
  "id": 8,
  "part": "小雅-鹿鸣之什-采薇",
  "title_en": "Xiao Ya · Cai Wei",
  "title_zh": "小雅·采薇",
  "title_short": "Gathering Vetch",
  "ancient": "采薇采薇、薇亦柔止。\n曰归曰归、心亦忧止。\n忧心烈烈、载饥载渴。\n我戍未定、靡使归聘。",
  "translation": "Let us gather the thorn-ferns, let us gather the thorn-ferns;\nThe thorn-ferns are now tender.\nWhen shall we return? When shall we return?\nOur hearts are sorrowful;\nOur hearts are sad and sorrowful;\nWe shall hunger, we shall thirst.\nWhile our service on guard is not finished,\nWe can send no one home to enquire about our families."
 },
 {
  "id": 9,
  "part": "小雅-鹿鸣之什-采薇",
  "title_en": "Xiao Ya · Cai Wei",
  "title_zh": "小雅·采薇",
  "title_short": "Gathering Vetch",
  "ancient": "采薇采薇、薇亦刚止。\n曰归曰归、岁亦阳止。\n王事靡盬、不遑启处。\n忧心孔疚、我行不来。",
  "translation": "Let us gather the thorn-ferns, let us gather the thorn-ferns;\nThe thorn-ferns are now hard.\nWhen shall we return? When shall we return?\nThe year will be in the tenth month.\nBut the king's business must not be slackly performed;\nWe shall have no leisure to rest.\nOur sorrowing hearts are in great distress;\nBut we shall not return from our expedition."
 },
 {
  "id": 10,
  "part": "小雅-鹿鸣之什-采薇",
  "title_en": "Xiao Ya · Cai Wei",
  "title_zh": "小雅·采薇",
  "title_short": "Gathering Vetch",
  "ancient": "彼尔维何、维常之华。\n彼路斯何、君子之车。\n戎车既驾、四牡业业。\n岂敢定居、一月三捷。",
  "translation": "What is that so gorgeous?\nIt is the flowers of the cherry tree.\nWhat carriage is that?\nIt is the carriage of our general.\nHis war carriage is yoked;\nThe four steeds are strong.\nDare we remain inactive?\nIn one month we shall have three victories."
 },
 {
  "id": 11,
  "part": "小雅-鹿鸣之什-采薇",
  "title_en": "Xiao Ya · Cai Wei",
  "title_zh": "小雅·采薇",
  "title_short": "Gathering Vetch",
  "ancient": "驾彼四牡、四牡騤騤。\n君子所依、小人所腓。\n四牡翼翼、象弭鱼服。\n岂不日戒、猃狁孔棘。",
  "translation": "The four steeds are yoked,\nThe four steeds, eager and strong;\nThe confidence of the general,\nThe protection of the men.\nThe four steeds move regularly, like wings;\nThere are the bow with its ivory ends, and the seal-skin quiver.\nShall we not daily warn one another?\nThe business of the Xian-yun is very urgent."
 },
 {
  "id": 12,
  "part": "小雅-鹿鸣之什-采薇",
  "title_en": "Xiao Ya · Cai Wei",
  "title_zh": "小雅·采薇",
  "title_short": "Gathering Vetch",
  "ancient": "昔我往矣、杨柳依依。\n今我来思、雨雪霏霏。\n行道迟迟、载渴载饥。\n我心伤悲、莫知我哀。",
  "translation": "At first, when we set out,\nThe willows were fresh and green;\nNow, when we shall be returning,\nThe snow will be falling in clouds.\nLong and tedious will be our marching;\nWe shall hunger; we shall thirst.\nOur hearts are wounded with grief,\nAnd no one knows our sadness."
 },
 {
  "id": 13,
  "part": "国风-郑风-子衿",
  "title_en": "Zheng Feng · Zi Jin",
  "title_zh": "郑风·子衿",
  "title_short": "Your Blue Collar",
  "ancient": "青青子衿、悠悠我心。\n纵我不往、子宁不嗣音。",
  "translation": "O you, with the blue collar, \nProlonged is the anxiety of my heart. \nAlthough I do not go [to you], \nWhy do you not continue your messages [to me]?"
 },
 {
  "id": 14,
  "part": "国风-郑风-子衿",
  "title_en": "Zheng Feng · Zi Jin",
  "title_zh": "郑风·子衿",
  "title_short": "Your Blue Collar",
  "ancient": "青青子佩、悠悠我思。\n纵我不往、子宁不来。",
  "translation": "O you with the blue [strings to your] girdle-gems, \nLong, long do I think of you.\n Although I do not go [to you],\n Why do you not come [to me]?"
 },
 {
  "id": 15,
  "part": "国风-郑风-子衿",
  "title_en": "Zheng Feng · Zi Jin",
  "title_zh": "郑风·子衿",
  "title_short": "Your Blue Collar",
  "ancient": "挑兮达兮、在城阙兮。\n一日不见、如三月兮。",
  "translation": "How volatile are you and dissipated, \nBy the look-out tower on the wall! \nOne day without the sight of you,\n Is like three months."
 },
 {
  "id": 16,
  "part": "国风-周南-汉广",
  "title_en": "Zhou Nan · Han Guang",
  "title_zh": "周南·汉广",
  "title_short": "Broad Han River",
  "ancient": "南有乔木、不可休息。\n汉有游女、不可求思。\n汉之广矣、不可泳思。\n江之永矣、不可方思。",
  "translation": "In the south rise the trees without branches, \nAffording no shelter. \nBy the Han are girls rambling about, \nBut it is vain to solicit them.\nThe breadth of the Han\nCannot be dived across;\nThe length of the Jiang\nCannot be navigated with a raft."
 },
 {
  "id": 17,
  "part": "国风-周南-汉广",
  "title_en": "Zhou Nan · Han Guang",
  "title_zh": "周南·汉广",
  "title_short": "Broad Han River",
  "ancient": "翘翘错薪、言刈其楚。\n之子于归、言秣其马。\n汉之广矣、不可泳思。\n江之永矣、不可方思。",
  "translation": "Many are the bundles of firewood; \nI would cut down the thorns [to form more]. \nThose girls that are going to their future home, \nI would feed their horses.\nThe breadth of the Han\nCannot be dived across;\nThe length of the Jiang\nCannot be navigated with a raft."
 },
 {
  "id": 18,
  "part": "国风-周南-汉广",
  "title_en": "Zhou Nan · Han Guang",
  "title_zh": "周南·汉广",
  "title_short": "Broad Han River",
  "ancient": "翘翘错薪、言刈其蒌。\n之子于归、言秣其驹。\n汉之广矣、不可泳思。\n江之永矣、不可方思。",
  "translation": "Many are the bundles of firewood; \nI would cut down the southern wood [to form more]. \nThose girls that are going to their future home, \nI would feed their colts.\nThe breadth of the Han\nCannot be dived across;\nThe length of the Jiang\nCannot be navigated with a raft."
 },
 {
  "id": 19,
  "part": "国风-王风-黍离",
  "title_en": "Wang Feng · Shu Li",
  "title_zh": "王风·黍离",
  "title_short": "Millet Drooping",
  "ancient": "彼黍离离、彼稷之苗。\n行迈靡靡、中心摇摇。\n知我者、谓我心忧、不知我者、谓我何求。\n悠悠苍天、此何人哉。",
  "translation": "There was the millet with its drooping heads; \nThere was the sacrificial millet coming into blade. \nSlowly I moved about, \nIn my heart all-agitated. \nThose who knew me, \nSaid I was sad at heart. \nThose who did not know me, \nSaid I was seeking for something. \nO distant and azure Heaven! \nBy what man was this [brought about]?"
 },
 {
  "id": 20,
  "part": "国风-王风-黍离",
  "title_en": "Wang Feng · Shu Li",
  "title_zh": "王风·黍离",
  "title_short": "Millet Drooping",
  "ancient": "彼黍离离、彼稷之穗。\n行迈靡靡、中心如醉。\n知我者、谓我心忧、不知我者、谓我何求。\n悠悠苍天、此何人哉。",
  "translation": "There was the millet with its drooping heads; \nThere was the sacrificial millet in the ear. \nSlowly I moved about, \nMy heart intoxicated, as it were, [with grief]. \nThose who knew me, \nSaid I was sad at heart. \nThose who did not know me, \nSaid I was seeking for something. \nO thou distant and azure Heaven! \nBy what man was this [brought about]?"
 },
 {
  "id": 21,
  "part": "国风-王风-黍离",
  "title_en": "Wang Feng · Shu Li",
  "title_zh": "王风·黍离",
  "title_short": "Millet Drooping",
  "ancient": "彼黍离离、彼稷之实。\n行迈靡靡、中心如噎。\n知我者、谓我心忧、不知我者、谓我何求。\n悠悠苍天、此何人哉。",
  "translation": "There was the millet with its drooping heads; \nThere was the sacrificial millet in grain. \nSlowly I moved about, \nAs if there were a stoppage at my heart. \nThose who knew me, \nSaid I was sad at heart. \nThose who did not know me, \nSaid I was seeking for something. \nO thou distant and azure Heaven! \nBy what man was this [brought about]?"
 },
 {
  "id": 22,
  "part": "小雅-都人士之什-采绿",
  "title_en": "Xiao Ya · Cai Lü",
  "title_zh": "小雅·采绿",
  "title_short": "Gathering Green",
  "ancient": "终朝采绿、不盈一掬。\n予发曲局、薄言归沐。",
  "translation": "All the morning I gather the king-grass,\nAnd do not collect enough to fill my hands.\nMy hair is in a wisp;\nI will go home and wash it."
 },
 {
  "id": 23,
  "part": "小雅-都人士之什-采绿",
  "title_en": "Xiao Ya · Cai Lü",
  "title_zh": "小雅·采绿",
  "title_short": "Gathering Green",
  "ancient": "终朝采蓝、不盈一襜。\n五日为期，六日不詹。",
  "translation": "All the morning I gather the indigo plant,\nAnd do not collect enough to fill my apron.\nFive days was the time agreed on;\nIt is the sixth, and I do not see him."
 },
 {
  "id": 24,
  "part": "小雅-都人士之什-采绿",
  "title_en": "Xiao Ya · Cai Lü",
  "title_zh": "小雅·采绿",
  "title_short": "Gathering Green",
  "ancient": "之子于狩，言韔其弓。\n之子于钓，言纶之绳。",
  "translation": "When he went a hunting,\nI put the bow in its case for him.\nWhen he went to fish,\nI arranged his line for him."
 },
 {
  "id": 25,
  "part": "小雅-都人士之什-采绿",
  "title_en": "Xiao Ya · Cai Lü",
  "title_zh": "小雅·采绿",
  "title_short": "Gathering Green",
  "ancient": "其钓维何，维鲂及鱮。\n维鲂及鱮，薄言观者。",
  "translation": "What did he take in angling?\nBream and tench;\nBream and tench,\nWhile people [looked on] to see."
 },
 {
  "id": 26,
  "part": "国风-秦风-无衣",
  "title_en": "Qin Feng · Wu Yi",
  "title_zh": "秦风·无衣",
  "title_short": "No Robe",
  "ancient": "岂曰无衣、与子同袍。\n王于兴师、修我戈矛、与子同仇。",
  "translation": "How shall it be said that you have no clothes?\nI will share my long robes with you.\nThe king is raising his forces;\nI will prepare my lance and spear,\nAnd will be your comrade."
 },
 {
  "id": 27,
  "part": "国风-秦风-无衣",
  "title_en": "Qin Feng · Wu Yi",
  "title_zh": "秦风·无衣",
  "title_short": "No Robe",
  "ancient": "岂曰无衣、与子同泽。\n王于兴师、修我矛戟、与子偕作。",
  "translation": "How shall it be said that you have no clothes?\nI will share my under clothes with you.\nThe king is raising his forces;\nI will prepare my spear and lance,\nAnd will take the field with you."
 },
 {
  "id": 28,
  "part": "国风-秦风-无衣",
  "title_en": "Qin Feng · Wu Yi",
  "title_zh": "秦风·无衣",
  "title_short": "No Robe",
  "ancient": "岂曰无衣、与子同裳。\n王于兴师、修我甲兵、与子偕行。",
  "translation": "How shall it be said that you have no clothes?\nI will share my lower garments with you.\nThe king is raising his forces;\nI will prepare my buffcoat and sharp weapons,\nAnd will march along with you."
 },
 {
  "id": 29,
  "part": "国风-豳风-东山",
  "title_en": "Bin Feng · Dong Shan",
  "title_zh": "豳风·东山",
  "title_short": "East Mountain",
  "ancient": "我徂东山、慆慆不归。\n我来自东、零雨其蒙。\n我东曰归、我心西悲。\n制彼裳衣、勿士行枚。\n蜎蜎者蠋、烝在桑野。\n敦彼独宿、亦在车下。",
  "translation": "We went to the hills of the east,\nAnd long were we there without returning,\nWhen we came back from the east,\nDown came the rain drizzlingly.\nWhen we were in the east, and it was said we should return,\nOur hearts were in the west and sad;\nBut there were they preparing our clothes for us,\nAs to serve no more in the ranks with the gags.\nCreeping about were the caterpillars,\nAll over the mulberry grounds;\nAnd quietly and solitarily did we pass the night,\nUnder our carriages."
 },
 {
  "id": 30,
  "part": "国风-豳风-东山",
  "title_en": "Bin Feng · Dong Shan",
  "title_zh": "豳风·东山",
  "title_short": "East Mountain",
  "ancient": "我徂东山、慆慆不归。\n我来自东、零雨其蒙。\n果裸之实、亦施于宇。\n伊威在室、蠨蛸在户。\n町疃鹿场、熠耀宵行。\n不可畏也、伊可怀也。",
  "translation": "We went to the hills of the east,\nAnd long were we there without returning,\nWhen we came back from the east,\nDown came the rain drizzlingly.\nThe fruit of the heavenly gourd,\nWould be hanging about our eaves;\nThe sowbug would be in our chambers;\nThe spiders' webs would be in our doors;\nOur paddocks would be deer-fields;\nThe fitful light of the glow-worms would be all about.\nThese thoughts made us apprehensive,\nAnd they occupied our breasts."
 },
 {
  "id": 31,
  "part": "国风-豳风-东山",
  "title_en": "Bin Feng · Dong Shan",
  "title_zh": "豳风·东山",
  "title_short": "East Mountain",
  "ancient": "我徂东山、慆慆不归。\n我来自东、零雨其蒙。\n鹳鸣于垤、妇叹于室。\n洒扫穹窒、我征聿至。\n有敦瓜苦、烝在栗薪。\n自我不见、于今三年。",
  "translation": "We went to the hills of the east,\nAnd long were we there without returning,\nOn our way back from the east,\nDown came the rain drizzlingly.\nThe cranes were crying on the ant-hills;\nOur wives were sighing in their rooms;\nThey had sprinkled and swept, and stuffed up all the crevices.\nSuddenly we arrived from the expedition,\nAnd there were the bitter gourds hanging,\nFrom the branches of the chestnut trees.\nSince we had seen such a sight,\nThree years were now elapsed."
 },
 {
  "id": 32,
  "part": "国风-豳风-东山",
  "title_en": "Bin Feng · Dong Shan",
  "title_zh": "豳风·东山",
  "title_short": "East Mountain",
  "ancient": "我徂东山、慆慆不归。\n我来自东、零雨其蒙。\n仓庚于飞、熠耀其羽。\n之子于归、皇驳其马。\n亲结其缡、九十其仪。\n其新孔嘉、其旧如之何。",
  "translation": "We went to the hills of the east,\nAnd long were we there without returning,\nOn our way back from the east,\nDown came the rain drizzlingly.\nThe oriole is flying about,\nNow here, now there, are its wings.\nThose young ladies are going to be married,\nWith their bay and red horses, flecked with white.\nTheir mothers have tied their sashes;\nComplete are their equipments.\nThe new matches are admirable;\nHow can the reunions of the old be expressed?"
 },
 {
  "id": 33,
  "part": "小雅-祈父之什-白驹",
  "title_en": "Xiao Ya · Bai Ju",
  "title_zh": "小雅·白驹",
  "title_short": "White Colt",
  "ancient": "皎皎白驹、食我场苗。\n絷之维之、以永今朝。\n所谓伊人、于焉逍遥。",
  "translation": "Let the brilliant white colt,\nFeed on the young growth of my vegetable garden.\nTether it by the foot, tie it by the collar,\nTo prolong this morning.\nSo may its owner of whom I think,\nSpend his time here at his ease!"
 },
 {
  "id": 34,
  "part": "小雅-祈父之什-白驹",
  "title_en": "Xiao Ya · Bai Ju",
  "title_zh": "小雅·白驹",
  "title_short": "White Colt",
  "ancient": "皎皎白驹、食我场藿。\n絷之维之、以永今夕。\n所谓伊人、于焉嘉客。",
  "translation": "Let the brilliant white colt,\nFeed on the bean sprouts of my vegetable garden.\nTether it by the foot, tie it by the collar,\nTo prolong this evening.\nSo may its owner of whom I think,\nBe here, an admired guest!"
 },
 {
  "id": 35,
  "part": "小雅-祈父之什-白驹",
  "title_en": "Xiao Ya · Bai Ju",
  "title_zh": "小雅·白驹",
  "title_short": "White Colt",
  "ancient": "皎皎白驹、贲然来思。\n尔公尔侯、逸豫无期。\n慎尔优游、勉尔遁思。",
  "translation": "If [you with] the brilliant white colt,\nWould brightly come to me,\nYou should be a duke, you should be a marquis,\nEnjoying yourself without end.\nBe on your guard against idly wandering;\nDeal vigorously with your thoughts of retirement."
 },
 {
  "id": 36,
  "part": "小雅-祈父之什-白驹",
  "title_en": "Xiao Ya · Bai Ju",
  "title_zh": "小雅·白驹",
  "title_short": "White Colt",
  "ancient": "皎皎白驹、在彼空谷。\n生刍一束、其人如玉。\n毋金玉尔音、而有遐心。",
  "translation": "The brilliant white colt,\nIs there in that empty valley,\nWith a bundle of fresh grass.\nIts owner is like a gem.\nDo not make the news of you rare as gold and gems,\nIndulging your purpose to abandon me."
 }
];
